CREATE DATABASE golf;
USE golf;

CREATE TABLE Spelare(
PersonNr VARCHAR(13) PRIMARY KEY,
Dob DATE NOT NULL,
Namn VARCHAR(45) NOT NULL,
Ålder INT 
);

CREATE TABLE Tävling(
Namn VARCHAR(45) PRIMARY KEY,
Datum DATE NOT NULL
);

CREATE TABLE Regn(
Typ VARCHAR(45) PRIMARY KEY,
Vindstyrka INT NOT NULL
);

CREATE TABLE Konstruktion(
SerialNr INT PRIMARY KEY,
Hårdhet INT NOT NULL
);

CREATE TABLE Jacka(
Märke VARCHAR(45) NOT NULL,
Storlek VARCHAR(4) NOT NULL,
Material VARCHAR(45) NOT NULL,
PersonNr VARCHAR(13) NOT NULL,
FOREIGN KEY(PersonNr) REFERENCES Spelare(PersonNr)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE Klubba(
Nr INT NOT NULL,
Material VARCHAR(45) NOT NULL,
PersonNr VARCHAR(13) NOT NULL,
SerialNr INT NOT NULL,
FOREIGN KEY(PersonNr) REFERENCES Spelare(PersonNr)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(SerialNr) REFERENCES Konstruktion(SerialNr)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE Delta(
PersonNr VARCHAR(13) NOT NULL,
Namn VARCHAR(45) NOT NULL,
FOREIGN KEY(PersonNr) REFERENCES Spelare(PersonNr)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(Namn) REFERENCES Tävling(Namn)
ON DELETE CASCADE
ON UPDATE CASCADE,
PRIMARY KEY(PersonNr,Namn)
);

CREATE TABLE Har(
Namn VARCHAR(45) NOT NULL,
Typ VARCHAR(45) NOT NULL,
Tidpunkt TIME NOT NULL,
FOREIGN KEY(Namn) REFERENCES Tävling(Namn)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(Typ) REFERENCES Regn(Typ)
ON DELETE CASCADE
ON UPDATE CASCADE,
PRIMARY KEY(Namn,Typ)
);



